### ISSUE TITLE
POST http://localhost:8100/server/signup.php 404 

### ISSUE THREAD

**Issue by kishandas** [arjunsk/Ionic-Shopping-Cart#1]

**Comment by kishandas** [comment]
please help me out from this error

**Comment by autoincr** [comment]
I am really sorry, if you are not able to configure this. I will soon be posting a video tutorial for the same. Currently I am busy with academics. Just follow my blog for the latest updates. 

Thank you.

**Comment by autoincr** [comment]
About the signup.php, you have to use the latest version of Foodkart v0.2

https://github.com/arjunsk/ionic-shopping-cart-2

https://github.com/arjunsk/ionic-shopping-cart-2/blob/master/server_side/signup.php
